name: Copilot Reviewer
on:
  pull_request:
    types: [opened, reopened, ready_for_review]

permissions:
  pull-requests: write

jobs:
  request:
    uses: CloudIngenium/.github/.github/workflows/request-copilot-review.yml@24fac1de6a37800bae89a7b4f858742c7a455043
    secrets: inherit
