name: Socket Security
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
permissions:
  contents: read
concurrency:
  group: socket-${{ github.ref }}
  cancel-in-progress: true
jobs:
  socket:
    uses: CloudIngenium/.github/.github/workflows/socket-security.yml@main
    secrets: inherit
