name: Socket Security
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
permissions:
  contents: read
concurrency:
  group: socket-${{ github.ref }}
  cancel-in-progress: true
jobs:
  socket:
    uses: CloudIngenium/.github/.github/workflows/socket-security.yml@24fac1de6a37800bae89a7b4f858742c7a455043
    secrets: inherit
